export const DATABASE_HEALTH_PORT = Symbol('DATABASE_HEALTH_PORT');
export const TRANSACTION_RUNNER = Symbol('TRANSACTION_RUNNER');
export const REQUEST_CONTEXT = Symbol('REQUEST_CONTEXT');
export const GRACEFUL_RESOURCE_REGISTRY = Symbol('GRACEFUL_RESOURCE_REGISTRY');
