packages:
  - apps/*
  - packages/*
allowBuilds:
  '@prisma/engines': true
  '@pb33f/openapi-changes': true
  '@scarf/scarf': false
  argon2: true
  esbuild: true
  prisma: true
minimumReleaseAgeExclude:
  - '@aws-sdk/client-s3@3.1104.0'
  - '@aws-sdk/s3-presigned-post@3.1104.0'
  - '@aws-sdk/s3-request-presigner@3.1104.0'
